#############################################################################
# Makefile for building: qtAndymoteServer
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  qtAndymoteServer.pro
# Template: app
# Command: /home/andy/raspi/qt5/bin/qmake -o Makefile qtAndymoteServer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/andy/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/andy/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../raspi/qt5pi/include -I../../raspi/qt5pi/include/QtNetwork -I../../raspi/qt5pi/include/QtCore -I. -I../../raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++
QMAKE         = /home/andy/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/andy/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/andy/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtAndymoteServer1.0.0
DISTDIR = /home/andy/QtApps/qtAndymoteServer/.tmp/qtAndymoteServer1.0.0
LINK          = /home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/andy/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/andy/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/andy/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/andy/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/home/andy/raspi/sysroot/usr/lib/arm-linux-gnueabihf -llirc_client -L/home/andy/raspi/qt5pi/lib -lQt5Network -lQt5Core -lpthread 
AR            = /home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		clserver.cpp \
		clGetRemotesResponder.cpp \
		clListKeysResponder.cpp \
		clServerResponder.cpp \
		clStartSending.cpp \
		clStopSending.cpp \
		clKeySeqResponder.cpp moc_clserver.cpp
OBJECTS       = main.o \
		clserver.o \
		clGetRemotesResponder.o \
		clListKeysResponder.o \
		clServerResponder.o \
		clStartSending.o \
		clStopSending.o \
		clKeySeqResponder.o \
		moc_clserver.o
DIST          = ../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../raspi/qt5/mkspecs/common/unix.conf \
		../../raspi/qt5/mkspecs/common/linux.conf \
		../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../raspi/qt5/mkspecs/qdevice.pri \
		../../raspi/qt5/mkspecs/features/device_config.prf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../raspi/qt5/mkspecs/qconfig.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_help.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf \
		../../raspi/qt5/mkspecs/features/spec_post.prf \
		../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../raspi/qt5/mkspecs/features/default_post.prf \
		../../raspi/qt5/mkspecs/features/link_pkgconfig.prf \
		../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../raspi/qt5/mkspecs/features/qt.prf \
		../../raspi/qt5/mkspecs/features/resources.prf \
		../../raspi/qt5/mkspecs/features/moc.prf \
		../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../raspi/qt5/mkspecs/features/yacc.prf \
		../../raspi/qt5/mkspecs/features/lex.prf \
		qtAndymoteServer.pro clserver.h \
		clGetRemotesResponder.h \
		clListKeysResponder.h \
		clServerResponder.h \
		clStartSending.h \
		clStopSending.h \
		requests.h \
		clKeySeqResponder.h \
		constants.h \
		utils.h \
		lircClient.h main.cpp \
		clserver.cpp \
		clGetRemotesResponder.cpp \
		clListKeysResponder.cpp \
		clServerResponder.cpp \
		clStartSending.cpp \
		clStopSending.cpp \
		clKeySeqResponder.cpp
QMAKE_TARGET  = qtAndymoteServer
DESTDIR       = 
TARGET        = qtAndymoteServer


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtAndymoteServer.pro ../../raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf ../../raspi/qt5/mkspecs/features/spec_pre.prf \
		../../raspi/qt5/mkspecs/common/unix.conf \
		../../raspi/qt5/mkspecs/common/linux.conf \
		../../raspi/qt5/mkspecs/common/sanitize.conf \
		../../raspi/qt5/mkspecs/common/gcc-base.conf \
		../../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../../raspi/qt5/mkspecs/common/g++-base.conf \
		../../raspi/qt5/mkspecs/common/g++-unix.conf \
		../../raspi/qt5/mkspecs/qdevice.pri \
		../../raspi/qt5/mkspecs/features/device_config.prf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../../raspi/qt5/mkspecs/qconfig.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_help.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../../raspi/qt5/mkspecs/features/qt_functions.prf \
		../../raspi/qt5/mkspecs/features/qt_config.prf \
		../../raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf \
		../../raspi/qt5/mkspecs/features/spec_post.prf \
		../../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../../raspi/qt5/mkspecs/features/toolchain.prf \
		../../raspi/qt5/mkspecs/features/default_pre.prf \
		../../raspi/qt5/mkspecs/features/resolve_config.prf \
		../../raspi/qt5/mkspecs/features/default_post.prf \
		../../raspi/qt5/mkspecs/features/link_pkgconfig.prf \
		../../raspi/qt5/mkspecs/features/warn_on.prf \
		../../raspi/qt5/mkspecs/features/qt.prf \
		../../raspi/qt5/mkspecs/features/resources.prf \
		../../raspi/qt5/mkspecs/features/moc.prf \
		../../raspi/qt5/mkspecs/features/unix/thread.prf \
		../../raspi/qt5/mkspecs/features/qmake_use.prf \
		../../raspi/qt5/mkspecs/features/file_copies.prf \
		../../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../../raspi/qt5/mkspecs/features/exceptions.prf \
		../../raspi/qt5/mkspecs/features/yacc.prf \
		../../raspi/qt5/mkspecs/features/lex.prf \
		qtAndymoteServer.pro \
		../../raspi/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Network.prl \
		../../raspi/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile qtAndymoteServer.pro
../../raspi/qt5/mkspecs/features/spec_pre.prf:
../../raspi/qt5/mkspecs/common/unix.conf:
../../raspi/qt5/mkspecs/common/linux.conf:
../../raspi/qt5/mkspecs/common/sanitize.conf:
../../raspi/qt5/mkspecs/common/gcc-base.conf:
../../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../../raspi/qt5/mkspecs/common/g++-base.conf:
../../raspi/qt5/mkspecs/common/g++-unix.conf:
../../raspi/qt5/mkspecs/qdevice.pri:
../../raspi/qt5/mkspecs/features/device_config.prf:
../../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../../raspi/qt5/mkspecs/qconfig.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3danimation.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3drender.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_charts.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gamepad.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_help.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_networkauth.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_nfc.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_purchasing.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qml.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quick.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_repparser.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_scxml.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_svg.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_uitools.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_websockets.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_x11extras.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../../raspi/qt5/mkspecs/features/qt_functions.prf:
../../raspi/qt5/mkspecs/features/qt_config.prf:
../../raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++/qmake.conf:
../../raspi/qt5/mkspecs/features/spec_post.prf:
../../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../../raspi/qt5/mkspecs/features/toolchain.prf:
../../raspi/qt5/mkspecs/features/default_pre.prf:
../../raspi/qt5/mkspecs/features/resolve_config.prf:
../../raspi/qt5/mkspecs/features/default_post.prf:
../../raspi/qt5/mkspecs/features/link_pkgconfig.prf:
../../raspi/qt5/mkspecs/features/warn_on.prf:
../../raspi/qt5/mkspecs/features/qt.prf:
../../raspi/qt5/mkspecs/features/resources.prf:
../../raspi/qt5/mkspecs/features/moc.prf:
../../raspi/qt5/mkspecs/features/unix/thread.prf:
../../raspi/qt5/mkspecs/features/qmake_use.prf:
../../raspi/qt5/mkspecs/features/file_copies.prf:
../../raspi/qt5/mkspecs/features/testcase_targets.prf:
../../raspi/qt5/mkspecs/features/exceptions.prf:
../../raspi/qt5/mkspecs/features/yacc.prf:
../../raspi/qt5/mkspecs/features/lex.prf:
qtAndymoteServer.pro:
../../raspi/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Network.prl:
../../raspi/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qtAndymoteServer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents clserver.h clGetRemotesResponder.h clListKeysResponder.h clServerResponder.h clStartSending.h clStopSending.h requests.h clKeySeqResponder.h constants.h utils.h lircClient.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp clserver.cpp clGetRemotesResponder.cpp clListKeysResponder.cpp clServerResponder.cpp clStartSending.cpp clStopSending.cpp clKeySeqResponder.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/andy/QtApps/qtAndymoteServer/pkg-config_wrapper.sh .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../raspi/qt5/mkspecs/features/data/dummy.cpp
	/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -pipe -march=armv7-a -marm -mthumb-interwork -mfpu=neon-vfpv4 -mtune=cortex-a7 -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/andy/raspi/sysroot -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_clserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clserver.cpp
moc_clserver.cpp: ../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtNetwork/QTcpServer \
		../../raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		../../raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		clServerResponder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		clserver.h \
		moc_predefs.h \
		../../raspi/qt5/bin/moc
	/home/andy/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/andy/raspi/qt5/mkspecs/devices/linux-rasp-pi2-g++ -I/home/andy/QtApps/qtAndymoteServer -I/home/andy/raspi/qt5pi/include -I/home/andy/raspi/qt5pi/include/QtNetwork -I/home/andy/raspi/qt5pi/include/QtCore -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/andy/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/andy/raspi/sysroot/usr/include -I/home/andy/raspi/sysroot/usr/include/arm-linux-gnueabihf clserver.h -o moc_clserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../raspi/qt5pi/include/QtCore/QCoreApplication \
		../../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qeventloop.h \
		clserver.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtNetwork/QTcpServer \
		../../raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		../../raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		clServerResponder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

clserver.o: clserver.cpp clserver.h \
		../../raspi/qt5pi/include/QtCore/QObject \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtNetwork/QTcpServer \
		../../raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		../../raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		../../raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		clServerResponder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/QEventLoop \
		../../raspi/qt5pi/include/QtCore/qeventloop.h \
		../../raspi/qt5pi/include/QtNetwork/QTcpSocket \
		../../raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		../../raspi/qt5pi/include/QtCore/QJsonDocument \
		../../raspi/qt5pi/include/QtCore/qjsondocument.h \
		../../raspi/qt5pi/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clserver.o clserver.cpp

clGetRemotesResponder.o: clGetRemotesResponder.cpp clGetRemotesResponder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		constants.h \
		../../raspi/qt5pi/include/QtCore/QString \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtCore/QJsonArray \
		../../raspi/qt5pi/include/QtCore/qjsonarray.h \
		../../raspi/qt5pi/include/QtCore/QDir \
		../../raspi/qt5pi/include/QtCore/qdir.h \
		../../raspi/qt5pi/include/QtCore/qfileinfo.h \
		../../raspi/qt5pi/include/QtCore/qfile.h \
		../../raspi/qt5pi/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clGetRemotesResponder.o clGetRemotesResponder.cpp

clListKeysResponder.o: clListKeysResponder.cpp clListKeysResponder.h \
		constants.h \
		../../raspi/qt5pi/include/QtCore/QString \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtCore/QJsonArray \
		../../raspi/qt5pi/include/QtCore/qjsonarray.h \
		../../raspi/qt5pi/include/QtCore/QFile \
		../../raspi/qt5pi/include/QtCore/qfile.h \
		../../raspi/qt5pi/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clListKeysResponder.o clListKeysResponder.cpp

clServerResponder.o: clServerResponder.cpp clServerResponder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		requests.h \
		clGetRemotesResponder.h \
		clListKeysResponder.h \
		constants.h \
		../../raspi/qt5pi/include/QtCore/QString \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtCore/QJsonArray \
		../../raspi/qt5pi/include/QtCore/qjsonarray.h \
		clKeySeqResponder.h \
		clStartSending.h \
		clStopSending.h \
		../../raspi/qt5pi/include/QtCore/QJsonDocument \
		../../raspi/qt5pi/include/QtCore/qjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clServerResponder.o clServerResponder.cpp

clStartSending.o: clStartSending.cpp clStartSending.h \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QString \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clStartSending.o clStartSending.cpp

clStopSending.o: clStopSending.cpp clStopSending.h \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QString \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clStopSending.o clStopSending.cpp

clKeySeqResponder.o: clKeySeqResponder.cpp clKeySeqResponder.h \
		utils.h \
		lircClient.h \
		/usr/include/lirc/lirc_client.h \
		../../raspi/qt5pi/include/QtCore/QString \
		../../raspi/qt5pi/include/QtCore/qstring.h \
		../../raspi/qt5pi/include/QtCore/qchar.h \
		../../raspi/qt5pi/include/QtCore/qglobal.h \
		../../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../../raspi/qt5pi/include/QtCore/qconfig.h \
		../../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../../raspi/qt5pi/include/QtCore/qlogging.h \
		../../raspi/qt5pi/include/QtCore/qflags.h \
		../../raspi/qt5pi/include/QtCore/qatomic.h \
		../../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../../raspi/qt5pi/include/QtCore/qmutex.h \
		../../raspi/qt5pi/include/QtCore/qnumeric.h \
		../../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../../raspi/qt5pi/include/QtCore/qbytearray.h \
		../../raspi/qt5pi/include/QtCore/qrefcount.h \
		../../raspi/qt5pi/include/QtCore/qnamespace.h \
		../../raspi/qt5pi/include/QtCore/qarraydata.h \
		../../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../../raspi/qt5pi/include/QtCore/QJsonObject \
		../../raspi/qt5pi/include/QtCore/qjsonobject.h \
		../../raspi/qt5pi/include/QtCore/qjsonvalue.h \
		../../raspi/qt5pi/include/QtCore/qiterator.h \
		../../raspi/qt5pi/include/QtCore/qpair.h \
		../../raspi/qt5pi/include/QtCore/QDebug \
		../../raspi/qt5pi/include/QtCore/qdebug.h \
		../../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../../raspi/qt5pi/include/QtCore/qhash.h \
		../../raspi/qt5pi/include/QtCore/qlist.h \
		../../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../../raspi/qt5pi/include/QtCore/qstringlist.h \
		../../raspi/qt5pi/include/QtCore/qregexp.h \
		../../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../../raspi/qt5pi/include/QtCore/qmap.h \
		../../raspi/qt5pi/include/QtCore/qtextstream.h \
		../../raspi/qt5pi/include/QtCore/qiodevice.h \
		../../raspi/qt5pi/include/QtCore/qobject.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../../raspi/qt5pi/include/QtCore/qmetatype.h \
		../../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../../raspi/qt5pi/include/QtCore/qlocale.h \
		../../raspi/qt5pi/include/QtCore/qvariant.h \
		../../raspi/qt5pi/include/QtCore/qshareddata.h \
		../../raspi/qt5pi/include/QtCore/qvector.h \
		../../raspi/qt5pi/include/QtCore/qpoint.h \
		../../raspi/qt5pi/include/QtCore/qset.h \
		../../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../../raspi/qt5pi/include/QtCore/QJsonArray \
		../../raspi/qt5pi/include/QtCore/qjsonarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clKeySeqResponder.o clKeySeqResponder.cpp

moc_clserver.o: moc_clserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clserver.o moc_clserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

